AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  mdpzoomcallback:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: mdp_zoom_callback
      Description: ''
      Handler: index.handler
      MemorySize: 128
      Role: >-
        arn:aws:iam::741365237744:role/service-role/mdp_zoom_callback-role-tycg9ufg
      Runtime: nodejs12.x
      Timeout: 3
